default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres
  password: 1q2w3e4r5t
development:
  <<: *default
  database: mall_rental_ricardo

test:
  <<: *default
  database: mall_rental_test

production:
  <<: *default
  database: mall_rental_production
