development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

default: &default
   host: localhost
   adapter: postgresql
   username: postgres
   password: 123456

test:
  <<: *default
  database: mall_rental_test

production:
  <<: *default
  database: mall_rental_production
